[package]
name = "mahjuro"
version = "0.4.3"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
bytemuck = { version = "1.23", features = ["derive"] }
cassowary = "0.3.0"
clap = { version = "4.5", features = ["derive"] }
env_logger = "0.11.8"
lyon_path = "1.0"
lyon_tessellation = "1.0"
fontdue = "0.8"
glam = { version = "0.30.9", features = ["bytemuck"] }
gltf = { version = "1.4.1", features = ["KHR_texture_transform"] }
image = { version = "0.25", default-features = false, features = ["png"] }
gilrs = "0.11.0"
log = "0.4.28"
pollster = "0.4.0"
rand = "0.10.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
ttf-parser = "0.25"
tokio = "1.51.0"
wgpu = "29.0.1"
winit = "0.30.12"
muda = "0.17.2"
chrono = "0.4.44"
dirs = "5"
arboard = "3.6.1"
enum_dispatch = "0.3"
rodio = { version = "0.19", features = ["vorbis"] }
rust-embed = { version = "8", features = ["include-exclude"] }
self_update = { version = "0.42", features = ["archive-zip", "archive-tar", "compression-flate2"] }
rayon = "1.11.0"
human_format = "1.2.1"

[dev-dependencies]
proptest = "1.6"
