image = "atlas.png"
tile_width = 512
tile_height = 512
columns = 5

layout = [
    "drought","whisper","gate","grove","coin",
    "rot","hermit","forest","bureaucrat","drunkard",
    "ash","furnace","relic","blight","hex",
    "famine","tempest","censor","mirror","counterweight",
    "tax_collector","dragon","house","dead_air","st_george",
]
