//! Procedural candle mesh — a revolved wax body plus a short wick stub.
//!
//! Built once at startup, instanced per candle via per-frame model matrices in
//! [`lit_mesh::LitMeshInstance`]. Local coordinates are normalized so the
//! candle's height runs from y=0 (base) to the top of the wax along +Y, with
//! the wick continuing slightly above. The wax body is shaped like a glass
//! votive — short and fat, roughly as wide as it is tall, with a slight
//! lip at the top and a thin wax pool dipping toward the wick.

use crate::render::lit_mesh::{MaterialParams, MeshCpu};
use crate::render::tile_glb::Vertex3dTex;

const RADIAL_SEGMENTS: usize = 24;

/// Profile point on the wax body. The mesh is generated by revolving these
/// points around the +Y axis.
struct ProfilePoint {
    r: f32,
    y: f32,
}

// Short, fat votive: roughly cylindrical with a small foot, a top rim,
// and a shallow wax pool around the wick. Total height ≈ 0.55 in local
// units; max radius ≈ 0.36 — i.e. wider than half-tall, the way a real
// votive cup looks.
const WAX_PROFILE: &[ProfilePoint] = &[
    ProfilePoint { r: 0.000, y: 0.000 }, // base center (closes bottom fan)
    ProfilePoint { r: 0.330, y: 0.000 }, // base outer
    ProfilePoint { r: 0.355, y: 0.025 }, // small foot bevel out
    ProfilePoint { r: 0.355, y: 0.060 }, // foot top
    ProfilePoint { r: 0.345, y: 0.090 }, // slight inward draft
    ProfilePoint { r: 0.350, y: 0.420 }, // straight body
    ProfilePoint { r: 0.360, y: 0.470 }, // top rim flare
    ProfilePoint { r: 0.355, y: 0.495 }, // rim peak
    ProfilePoint { r: 0.330, y: 0.510 }, // rim inner edge
    ProfilePoint { r: 0.250, y: 0.520 }, // wax-pool slope
    ProfilePoint { r: 0.140, y: 0.535 }, // pool dip
    ProfilePoint { r: 0.060, y: 0.548 }, // pool around wick
    ProfilePoint { r: 0.000, y: 0.555 }, // close top (wick base)
];

fn build_revolved_mesh(profile: &[ProfilePoint], drip_amplitude: f32) -> MeshCpu {
    let n_radial = RADIAL_SEGMENTS;
    let n_profile = profile.len();
    let mut vertices: Vec<Vertex3dTex> = Vec::with_capacity(n_profile * (n_radial + 1));
    let mut indices: Vec<u32> = Vec::new();

    for (pi, p) in profile.iter().enumerate() {
        for ri in 0..=n_radial {
            let theta = (ri as f32) / (n_radial as f32) * std::f32::consts::TAU;
            // 3-lobed drip ridge perturbation on the radius — only on the
            // straight body sections (skip the very ends so the closing
            // verts stay on-axis).
            let drip = if pi > 1 && pi + 2 < n_profile {
                drip_amplitude * (3.0 * theta).sin().abs() * 0.6
            } else {
                0.0
            };
            let r = p.r + drip;
            let x = r * theta.cos();
            let z = r * theta.sin();
            let y = p.y;

            // Local profile tangent (in r,y plane) for the surface normal.
            // Use a forward/backward neighbour where available.
            let (dr, dy) = if pi == 0 {
                let q = &profile[1];
                (q.r - p.r, q.y - p.y)
            } else if pi + 1 == n_profile {
                let q = &profile[pi - 1];
                (p.r - q.r, p.y - q.y)
            } else {
                let a = &profile[pi - 1];
                let b = &profile[pi + 1];
                (b.r - a.r, b.y - a.y)
            };
            // Outward-pointing normal in (r,y): rotate tangent +90°.
            let (nr, ny) = {
                let raw = (dy, -dr);
                let len = (raw.0 * raw.0 + raw.1 * raw.1).sqrt().max(1e-6);
                (raw.0 / len, raw.1 / len)
            };
            // Lift the (r,y) normal back into 3D.
            let nx = nr * theta.cos();
            let nz = nr * theta.sin();
            let normal = [nx, ny, nz];

            let u = (ri as f32) / (n_radial as f32);
            let v = 1.0 - p.y;

            vertices.push(Vertex3dTex {
                position: [x, y, z],
                normal,
                uv: [u, v],
            });
        }
    }

    let row_stride = n_radial + 1;
    for pi in 0..(n_profile - 1) {
        for ri in 0..n_radial {
            let i00 = (pi * row_stride + ri) as u32;
            let i01 = (pi * row_stride + ri + 1) as u32;
            let i10 = ((pi + 1) * row_stride + ri) as u32;
            let i11 = ((pi + 1) * row_stride + ri + 1) as u32;
            // CCW so the outward normal direction matches our normal calc.
            indices.push(i00);
            indices.push(i10);
            indices.push(i01);
            indices.push(i01);
            indices.push(i10);
            indices.push(i11);
        }
    }

    // Bottom cap: a fan from (0, 0, 0) to the first ring of body verts.
    let center_idx = vertices.len() as u32;
    vertices.push(Vertex3dTex {
        position: [0.0, 0.0, 0.0],
        normal: [0.0, -1.0, 0.0],
        uv: [0.5, 0.5],
    });
    // Use the second profile row (pi=1, full base radius) for the cap edge so
    // the cap is flush with the cylindrical base.
    for ri in 0..n_radial {
        let a = (1 * row_stride + ri) as u32;
        let b = (1 * row_stride + ri + 1) as u32;
        indices.push(center_idx);
        indices.push(b);
        indices.push(a);
    }

    MeshCpu {
        vertices,
        indices,
        default_material: MaterialParams::wax(),
    }
}

/// Build the wax body mesh (large primitive).
pub fn build_candle_wax_mesh() -> MeshCpu {
    build_revolved_mesh(WAX_PROFILE, 0.010)
}

/// Build the wick mesh — a short, dark cylinder centered on the wax tip.
pub fn build_candle_wick_mesh() -> MeshCpu {
    let n_radial = 8;
    let r = 0.018;
    let y0 = 0.548; // sits in the wax pool, just below the actual top
    let y1 = 0.610; // wick tip — short stub poking out of the votive
    let mut vertices: Vec<Vertex3dTex> = Vec::with_capacity((n_radial + 1) * 2 + 2);
    let mut indices: Vec<u32> = Vec::new();

    for ri in 0..=n_radial {
        let theta = (ri as f32) / (n_radial as f32) * std::f32::consts::TAU;
        let nx = theta.cos();
        let nz = theta.sin();
        // Bottom ring.
        vertices.push(Vertex3dTex {
            position: [r * nx, y0, r * nz],
            normal: [nx, 0.0, nz],
            uv: [(ri as f32) / (n_radial as f32), 0.0],
        });
        // Top ring.
        vertices.push(Vertex3dTex {
            position: [r * nx, y1, r * nz],
            normal: [nx, 0.0, nz],
            uv: [(ri as f32) / (n_radial as f32), 1.0],
        });
    }
    for ri in 0..n_radial {
        let i00 = (ri * 2) as u32;
        let i01 = (ri * 2 + 1) as u32;
        let i10 = (ri * 2 + 2) as u32;
        let i11 = (ri * 2 + 3) as u32;
        indices.push(i00);
        indices.push(i10);
        indices.push(i01);
        indices.push(i01);
        indices.push(i10);
        indices.push(i11);
    }
    // Top cap (small disc so the wick reads as solid).
    let center_idx = vertices.len() as u32;
    vertices.push(Vertex3dTex {
        position: [0.0, y1, 0.0],
        normal: [0.0, 1.0, 0.0],
        uv: [0.5, 0.5],
    });
    for ri in 0..n_radial {
        let a = (ri * 2 + 1) as u32;
        let b = (ri * 2 + 3) as u32;
        indices.push(center_idx);
        indices.push(a);
        indices.push(b);
    }

    MeshCpu {
        vertices,
        indices,
        default_material: MaterialParams::wick(),
    }
}

/// Wick tip y in local mesh units, used by the scene to position flames and
/// point lights at the actual top of the candle.
pub const WICK_TIP_Y: f32 = 0.610;
