//! Device-agnostic UI actions (keyboard / gamepad / mouse routing).

/// Logical UI actions (device-agnostic).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum UiAction {
    FocusNext,
    FocusPrev,
    FocusDown,
    FocusUp,
    Confirm,
    ConfirmRelease,
    Cancel,
    CancelRelease,
    ScoreHand,
    TriggerStructure,
    CommitDiscard,
    InvertSelection,
    UndoDiscard,
    FocusPlayButton,
    FocusDiscardButton,
    NavigateHudNext,
    NavigateHudPrev,
    SortBySuit,
    SortByRank,
    TabNext,
    TabPrev,
    PageNext,
    PagePrev,
    Pause,
    Help,
    Delete,
    DebugBlowWind,
    DebugToggleAxes,
    NorthFacePress,
    WestFacePress,
    WestFaceRelease,
    TixelsLoadImage,
    TixelsResolutionDown,
    TixelsResolutionUp,
    TixelsTileDown,
    TixelsTileUp,
    TixelsToggleBayer,
    TixelsToggleColor,
    TixelsReset,
}
